#!/bin/bash
# aur-chroot - build packages with chroot
set -o errexit
readonly argv0=chroot
readonly PATH=/bin:/usr/bin
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

machine=$(uname -m)
readonly machine

# default arguments
directory=/var/lib/aurbuild/$machine
mkchrootpkg_args=(-cu)
mkchrootpkg_bindmounts_ro=()
bindmounts_ro=()

# default options
prepare=1 build=1

ignore_defaults() {
    awk '/^RootDir/ || /^DBPath/ || /^HookDir/ || /^GPGDir/ || /^LogFile/ {
        next
    } { print }'
}

host_with_cache() {
    printf '[%s]\n' options
    pacman-conf --verbose CacheDir

    for a in "$@"; do
        printf '[%s]\n' "$a"
        pacman-conf --repo "$a"
    done
}

trap_exit() {
    if ! [[ -o xtrace ]]; then
        rm -rf "$tmp"
    fi
}

usage() {
    printf >&2 'usage: %s [-d repo] [-CDM path] -- <mkchrootpkg args>\n' "$argv0"
    exit 1
}

source /usr/share/makepkg/util/parseopts.sh

opt_short='d:C:D:M:'
opt_long=('database' 'directory' 'pacman-conf' 'makepkg-conf' 'no-build' 'no-prepare')
opt_hidden=('dump-options')

if ! parseopts "$opt_short" "${opt_long[@]}" "${opt_hidden[@]}" -- "$@"; then
    usage
fi
set -- "${OPTRET[@]}"

# FIXME: add --sysroot to set pacconf host, see pacutils-sysroot(7)
unset pacman_conf makepkg_conf host_repo server
while true; do
    case "$1" in
        -d|--database) shift; host_repo+=("$1") ;;
        -D|--directory) shift; directory=$1 ;;
        -C|--pacman-conf) shift; pacman_conf=$1 ;;
        -M|--makepkg-conf) shift; makepkg_conf=$1 ;;
        --no-build)     build=0 ;;
        --no-prepare)   prepare=0 ;;
        --dump-options) printf -- '--%s\n' "${opt_long[@]}" ;
                        printf -- '%s' "${opt_short}" | sed 's/.:\?/-&\n/g' ;
                        exit ;;
        --) shift; break ;;
    esac
    shift
done
unset opt_short opt_long OPTRET

tmp=$(mktemp -d)
trap 'trap_exit' EXIT

# reset default mkchrootpkg arguments
if (($#)); then
    mkchrootpkg_args=("$@")
fi

# baseline configuration
pacman_conf=${pacman_conf-/usr/share/artools/pacman-lib32.conf}
makepkg_conf=${makepkg_conf-/usr/share/artools/makepkg.conf}

# CacheDir will be replaced by artools (#416)
host_with_cache "${host_repo[@]}" >"$tmp"/custom.conf

# bind mount all file:// paths to container (#461)
while read -r key _ value; do
    case $key=$value in
        Server=file://*)
            bindmounts_ro+=("-r ${value#file://}")
            mkchrootpkg_bindmounts_ro+=(-D "${value#file://}") ;;
    esac
done < "$tmp"/custom.conf

if ((prepare)); then
    # do not print DBPath (#412)
    pacman-conf -c "$pacman_conf" | ignore_defaults \
        | cat - "$tmp"/custom.conf >"$tmp"/pacman.conf

    if [[ -f $directory/root/.artools ]]; then
        sudo chroot-run -C "$tmp"/pacman.conf -M "$makepkg_conf" \
             "${bindmounts_ro[@]}" "$directory"/root pacman -Syu --noconfirm
    else
        # parent path is not created by mkchroot (#371)
        if [[ ! -d $directory ]]; then
            sudo install -d "$directory" -m 755 -v
        fi

        sudo mkchroot -C "$tmp"/pacman.conf -M "$makepkg_conf" \
             "$directory"/root base-devel
    fi
fi

if ((build)); then
    sudo --preserve-env=GNUPGHOME,PKGDEST mkchrootpkg -r "$directory" \
         "${mkchrootpkg_bindmounts_ro[@]}" "${mkchrootpkg_args[@]}"
else
    printf >&2 'container path: %q\n' "$directory"
    exit 0
fi

# vim: set et sw=4 sts=4 ft=sh:
